application: problem-chimp
version: 1
runtime: python
api_version: 1

mode: development
media_root: media # Relative path from content folder.
media_url: /media # URL where the media files are served from.
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.sorter.SorterPlugin
    - hyde.ext.plugins.syntext.SyntextPlugin
    - hyde.ext.plugins.textlinks.TextlinksPlugin
context:
    data:
        site_title: Heather McCartney
        author:
            name: Heather McCartney
            url: "http://www.problemchimp.org"
        home_url: index.html
        menu:
            - title: Home
              type: node
              url: /
            - title: Work
              type: node
              url: /work
            - title: Contact
              type: node
              url: /contact
sorter:
    time:
        attr:
            - meta.created
        reverse: true
        filters:
            source.kind: html
            meta.listable: true
